### ISSUE TITLE
Is it normal when i publish some messages like this?

### ISSUE THREAD

**Issue by fengrujun** [mgdm/Mosquitto-PHP#11]
mytest.php:
$client = new Mosquitto\Client();
$client->connect("x.x.x.x", 1883, 60);
 
while ($client->loop() == 0) {
	$message = "Test message at " . date("Y-m-d H:i:s");
	$client->publish('mytopic', $message, 0, false);
	$client->loop();
	sleep(1);
}

When i first use browser open  mytest.php ,the subscribe side receive the message sucessfully,but i close the page,the subscribe side still can receive the message ,what's going wrong?

**Comment by mgdm** [comment]
You need to call `$client->loop()` to make the underlying library process its messages. I've added an example to the README.
