### ISSUE TITLE
windows install

### ISSUE THREAD

**Issue by happyuser007** [mgdm/Mosquitto-PHP#117]
I have a vista computer with php5.2.5 What would be the necessary updating to do for mosquitto_php usage? And could you indicate some how-to to install the library because all references on the net tell about linux install. (I have a ESP8266 device publishing messages I would like to deal with them making computing on payload).
Thank you for any advice. Regards

**Comment by bbcmgdm** [comment]
Hi,
Unfortunately neither that Windows version nor PHP version are supported any more (in fact, this extension has never worked on PHP versions before 5.3). You'd need to upgrade both before you can use this.

**Comment by mgdm** [comment]
Hi,
Unfortunately neither that Windows version nor PHP version are supported any more (in fact, this extension has never worked on PHP versions before 5.3). You'd need to upgrade both before you can use this.
