### ISSUE TITLE
Can not install on Ubuntu 12.04 with Mosquite 3.1

### ISSUE THREAD

**Issue by ajt2** [mgdm/Mosquitto-PHP#12]
||/ Name                         Version                      Description
+++-============================-============================-========================================================================
ii  libmosquitto0                0.15-0ubuntu1.12.04.1        MQTT version 3.1 client library
ii  libmosquitto0-dev            0.15-0ubuntu1.12.04.1        MQTT version 3.1 client library, development files
ii  mosquitto-clients            0.15-0ubuntu1.12.04.1        Mosquitto command line MQTT clients

$ sudo pecl install Mosquitto-alpha
downloading Mosquitto-0.2.1.tgz ...
Starting to download Mosquitto-0.2.1.tgz (15,958 bytes)
......done: 15,958 bytes
4 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
Please provide the prefix of the libmosquitto installation [autodetect] : 
building in /tmp/pear/temp/pear-build-rootEO3vH6/Mosquitto-0.2.1
running: /tmp/pear/temp/Mosquitto/configure --with-mosquitto
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20121212
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for mosquitto support... yes, shared
checking for mosquitto files in default path... checking /usr... found in /usr
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... no
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) nawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/temp/pear-build-rootEO3vH6/Mosquitto-0.2.1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/Mosquitto -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootEO3vH6/Mosquitto-0.2.1/include -I/tmp/pear/temp/pear-build-rootEO3vH6/Mosquitto-0.2.1/main -I/tmp/pear/temp/Mosquitto -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/Mosquitto/mosquitto.c -o mosquitto.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/Mosquitto -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootEO3vH6/Mosquitto-0.2.1/include -I/tmp/pear/temp/pear-build-rootEO3vH6/Mosquitto-0.2.1/main -I/tmp/pear/temp/Mosquitto -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/Mosquitto/mosquitto.c  -fPIC -DPIC -o .libs/mosquitto.o
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client___construct':
/tmp/pear/temp/Mosquitto/mosquitto.c:111:2: warning: passing argument 2 of 'mosquitto_new' makes pointer from integer without a cast [enabled by default]
/usr/include/mosquitto.h:196:34: note: expected 'void *' but argument is of type 'zend_bool'
/tmp/pear/temp/Mosquitto/mosquitto.c:111:2: error: too many arguments to function 'mosquitto_new'
/usr/include/mosquitto.h:196:34: note: declared here
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_setWill':
/tmp/pear/temp/Mosquitto/mosquitto.c:284:2: warning: passing argument 3 of 'mosquitto_will_set' makes pointer from integer without a cast [enabled by default]
/usr/include/mosquitto.h:268:20: note: expected 'const char *' but argument is of type 'int'
/tmp/pear/temp/Mosquitto/mosquitto.c:284:2: warning: passing argument 4 of 'mosquitto_will_set' makes integer from pointer without a cast [enabled by default]
/usr/include/mosquitto.h:268:20: note: expected 'uint32_t' but argument is of type 'void *'
/tmp/pear/temp/Mosquitto/mosquitto.c:284:2: warning: passing argument 5 of 'mosquitto_will_set' makes pointer from integer without a cast [enabled by default]
/usr/include/mosquitto.h:268:20: note: expected 'const uint8_t *' but argument is of type 'long int'
/tmp/pear/temp/Mosquitto/mosquitto.c:284:2: error: too few arguments to function 'mosquitto_will_set'
/usr/include/mosquitto.h:268:20: note: declared here
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_connect':
/tmp/pear/temp/Mosquitto/mosquitto.c:355:3: error: too few arguments to function 'mosquitto_connect'
/usr/include/mosquitto.h:322:20: note: declared here
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_onConnect':
/tmp/pear/temp/Mosquitto/mosquitto.c:418:2: warning: passing argument 2 of 'mosquitto_connect_callback_set' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:618:21: note: expected 'void (*)(void *, int)' but argument is of type 'void (*)(struct mosquitto *, void *, int)'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_onDisconnect':
/tmp/pear/temp/Mosquitto/mosquitto.c:452:2: warning: passing argument 2 of 'mosquitto_disconnect_callback_set' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:634:21: note: expected 'void (*)(void *)' but argument is of type 'void (*)(struct mosquitto *, void *, int)'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_onSubscribe':
/tmp/pear/temp/Mosquitto/mosquitto.c:520:2: warning: passing argument 2 of 'mosquitto_subscribe_callback_set' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:693:21: note: expected 'void (*)(void *, uint16_t,  int,  const uint8_t *)' but argument is of type 'void (*)(struct mosquitto *, void *, int,  int,  const int *)'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_onUnsubscribe':
/tmp/pear/temp/Mosquitto/mosquitto.c:554:2: warning: passing argument 2 of 'mosquitto_unsubscribe_callback_set' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:710:21: note: expected 'void (*)(void *, uint16_t)' but argument is of type 'void (*)(struct mosquitto *, void *, int)'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_onMessage':
/tmp/pear/temp/Mosquitto/mosquitto.c:588:2: warning: passing argument 2 of 'mosquitto_message_callback_set' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:673:21: note: expected 'void (*)(void *, const struct mosquitto_message *)' but argument is of type 'void (*)(struct mosquitto *, void *, const struct mosquitto_message *)'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_publish':
/tmp/pear/temp/Mosquitto/mosquitto.c:667:2: warning: passing argument 2 of 'mosquitto_publish' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:395:20: note: expected 'uint16_t *' but argument is of type 'int *'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_subscribe':
/tmp/pear/temp/Mosquitto/mosquitto.c:692:2: warning: passing argument 2 of 'mosquitto_subscribe' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:417:20: note: expected 'uint16_t *' but argument is of type 'int *'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_unsubscribe':
/tmp/pear/temp/Mosquitto/mosquitto.c:716:2: warning: passing argument 2 of 'mosquitto_unsubscribe' from incompatible pointer type [enabled by default]
/usr/include/mosquitto.h:438:20: note: expected 'uint16_t *' but argument is of type 'int *'
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'zim_Mosquitto_Client_loop':
/tmp/pear/temp/Mosquitto/mosquitto.c:740:2: error: too many arguments to function 'mosquitto_loop'
/usr/include/mosquitto.h:503:20: note: declared here
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'mosquitto_client_object_destroy':
/tmp/pear/temp/Mosquitto/mosquitto.c:796:2: error: too many arguments to function 'mosquitto_loop'
/usr/include/mosquitto.h:503:20: note: declared here
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'php_mosquitto_handle_errno':
/tmp/pear/temp/Mosquitto/mosquitto.c:847:12: warning: assignment makes pointer from integer without a cast [enabled by default]
/tmp/pear/temp/Mosquitto/mosquitto.c: In function 'php_mosquitto_connect_callback':
/tmp/pear/temp/Mosquitto/mosquitto.c:872:10: warning: assignment makes pointer from integer without a cast [enabled by default]
make: *** [mosquitto.lo] Error 1
ERROR: `make' failed

**Comment by breagan** [comment]
Installed newest version of MQTT, working with all clients. 

Used:
sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa 

(Google MQTTLens, command line and ESP8266 running nodemcu)
Sub and Pub working on all clients.

sudo pecl install Mosquitto-alpha
>could not extract the package.xml file from "/build/buildd/php5-5.5.9+dfsg/pear-build-download/Mosquitto-0.2.2.tgz"
>Download of "pecl/Mosquitto" succeeded, but it is not a valid package archive
>Error: cannot download "pecl/Mosquitto" 
>Download failed
>Install failed

Tried manual;

libmosquitto.so.1 in the /usr/lib dir.

sudo phpize5
>Gonfiguring for:
>PHP Api Version:                20121113
>Zend Module Api No:         20121212
>Zend Extension Api No:     22012212

sudo ./configure --with-mosquitto=/usr/lib/
...
>checking for mosquitto support... yes, shared
>checking for mosquitto files in default path... not found
>configure: error: Please reinstall the mosquitto distribution

sudo apt-get install mosquitto 
> mosquitto is already the newest version.

Ubuntu 14.04.1 LTS  KDE

Any ideas?

Thank you!

**Comment by mgdm** [comment]
The path in the configure command isn't quite right. Try this?

```bash
 sudo ./configure --with-mosquitto=/usr
```

**Comment by breagan** [comment]
Hmmmm..    no luck with that. 
Also tried:
sudo ./configure --with-mosquitto --with-libdir=/usr
sudo ./configure --with-mosquitto=/usr --with-libdir=/usr
And as many other combinations as I could think of.

The error diagnostic states "checking for mosquitto files in default path... not found".
Is it possible that .configure is looking for files other than the libmosquitto.so.1 file?  Or, do I need to untar the gz archive in a specific path?

Thanks for the fast reply!!

**Comment by breagan** [comment]
__Here is an update.
I have a raspberry running MQTT also.  I attempted to install via pecl.  For some reason pecl was able to download the package and begin the build.
However, I got the same error: "checking for mosquitto files in default path... not found"__

>pi@raspberrypi ~ $ sudo pecl install Mosquitto-alpha
>WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading Mosquitto-0.2.2.tgz ...
Starting to download Mosquitto-0.2.2.tgz (16,018 bytes)
......done: 16,018 bytes
4 source files, building
running: phpize
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525
Please provide the prefix of the libmosquitto installation [autodetect] :
building in /tmp/pear/temp/pear-build-rootV3thC9/Mosquitto-0.2.2
running: /tmp/pear/temp/Mosquitto/configure --with-mosquitto
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... armv6l-unknown-linux-gnueabihf
checking host system type... armv6l-unknown-linux-gnueabihf
checking target system type... armv6l-unknown-linux-gnueabihf
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
checking for PHP extension directory... /usr/lib/php5/20100525+lfs
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for mosquitto support... yes, shared
checking for mosquitto files in default path... not found
configure: error: Please reinstall the mosquitto distribution
ERROR: `/tmp/pear/temp/Mosquitto/configure --with-mosquitto' failed

__I also tried /usr and /usr/lib when prompted at:__
>Please provide the prefix of the libmosquitto installation [autodetect]

**Comment by mgdm** [comment]
Oh, have you got the `libmosquitto-dev` package installed?

**Comment by breagan** [comment]
Oh...
Well that did it!
Thank you!

**Comment by Albinv06** [comment]
how to install the Mosquitto-alpha. i'm new this.please help me.
