### ISSUE TITLE
Can't know next step to make Mosquitto-PHP works

### ISSUE THREAD

**Issue by nintu-cto** [mgdm/Mosquitto-PHP#20]
I just installed Mosquitto 1.3.4.1 on Mac OS X with:
- brew install mosquito

Tried in my terminal to test it with : 
-  mosquitto_sub -h 127.0.0.1 -t "test"
  and
- mosquitto_pub -h 127.0.0.1 -t "test" -m "hey"

Working too.

Now I would like to use it with PHP, more precisely to publish from PHP. I tried to install your Mosquitto-PHP with : 
- pecl install Mosquitto-alpha

It didn't work from the first try because I had a "can't execute 'make'" so I had to do that : 
- xcode-select --install
  and 
- sudo pecl install memcache
  (find this solution online on http://stackoverflow.com/questions/19531262/cant-phpize-or-configure-an-extension-in-os-x-10-9-mavericks)

No errors so I suppose that's installed. I added extension=mosquitto.so to my php.ini, the one that's referred in Loaded Configuration File (=/usr/local/php5/lib/php.ini). But when I try the exemple code, I've this error : 
- Fatal error: Class 'Mosquitto\Client' not found in (...)

Do someone know which step I missed ?

Best regards.

Daniel Costa

**Comment by bclouser** [comment]
I have the same error in my PHP. I got everything installed, I am running on ubuntu 12.04.

This must be something simple... :/

**Comment by bclouser** [comment]
Actually it seems this only happens when i try to run the script via terminal. If i hit it from the browser though, it just loads forever, no text is printed on the screen.

**Comment by gjt211** [comment]
I have the same problem and dont know how to fix it. Google doesn't provide and ideas.
Has anyone solved this yet?

**Comment by jvoegeli** [comment]
Did anyone come up with an answer to this issue? I have banged my head against the wall for hours with no luck haha!

**Comment by bclouser** [comment]
Oh man, I don't remember exactly how i fixed this but I believe in the end it was just a configuration issue with the php module. 

I am by know means a php expert but looking at my current ubuntu system (which is acting as my mosquitto broker via php)  I have this file: /etc/php5/mods-available/mosquitto.ini.  This simply has the contents: 
extension=mosquitto.so


See if you have that file? Add it if you don't?

If i remember exactly what I did I will update... Good Luck!

**Comment by jvoegeli** [comment]
File is there I wonder if my php.ini file isn't quite right. Anyone care to share what is needed in there to get this to work or point to that new file?

**Comment by bclouser** [comment]
Here is my /etc/php5/apache2/php.ini file.

The important piece to note is the "extension=mosquitto.so"
[php.ini.txt](https://github.com/mgdm/Mosquitto-PHP/files/123883/php.ini.txt)
