### ISSUE TITLE
Problem publishing with QOS = 2 

### ISSUE THREAD

**Issue by pdstefan** [mgdm/Mosquitto-PHP#27]
Hi , 

I`m trying to publish on a queue using QOS 2 , with no luck so far. 

Using :
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
libmosquitto version 1.2.3 
Extension version : 0.2.2 
mosquitto version 1.4.2 (build date 2015-05-25 18:51:47+0300)

Code: 
```
   $mqtt_client = new Mosquitto\Client();
   $mqtt_client->connect('192.168.0.50', 1883, 5);
   $mid = $mqtt_client->publish('/2/orders', 'TEST' , 2 , false  );   
   $mqtt_client->disconnect();
```
If I change the qos value to 0 or 1 , it works flawlessly.  I`ve tested all scenarios qos 2 does not work, the output is below. (as a side note : I`ve tested this code with HiveMQ as well. Ver 1.5 works, but starting with ver 2, it fails as well). 

Debug log from mosquitto :  
```
1432571507: New connection from 192.168.0.112 on port 1883.
1432571507: Client lens_kPWHtQiFUMTz2h4fbBfma4gxR0p already connected, closing old connection.
1432571507: Client lens_kPWHtQiFUMTz2h4fbBfma4gxR0p disconnected.
1432571507: New client connected from 192.168.0.112 as lens_kPWHtQiFUMTz2h4fbBfma4gxR0p (c1, k120).
1432571507: Sending CONNACK to lens_kPWHtQiFUMTz2h4fbBfma4gxR0p (0, 0)
1432571515: Received SUBSCRIBE from lens_kPWHtQiFUMTz2h4fbBfma4gxR0p
1432571515: 	# (QoS 0)
1432571515: lens_kPWHtQiFUMTz2h4fbBfma4gxR0p 0 #
1432571515: Sending SUBACK to lens_kPWHtQiFUMTz2h4fbBfma4gxR0p
1432571527: New connection from 192.168.0.29 on port 1883.
1432571527: New client connected from 192.168.0.29 as mosq/vtPkkP@`EJ]WH5fh\E (c1, k5).
1432571527: Sending CONNACK to mosq/vtPkkP@`EJ]WH5fh\E (0, 0)
1432571527: Received PUBLISH from mosq/vtPkkP@`EJ]WH5fh\E (d0, q2, r0, m1, '/2/jeg', ... (4 bytes))
1432571527: Sending PUBREC to mosq/vtPkkP@`EJ]WH5fh\E (Mid: 1)
1432571529: Received DISCONNECT from mosq/vtPkkP@`EJ]WH5fh\E
1432571529: Client mosq/vtPkkP@`EJ]WH5fh\E disconnected.
1432571555: New connection from 192.168.0.29 on port 1883.
1432571555: New client connected from 192.168.0.29 as mosq/EiEjh;8c\ssqA3Nu_Q (c1, k5).
1432571555: Sending CONNACK to mosq/EiEjh;8c\ssqA3Nu_Q (0, 0)
1432571555: Received PUBLISH from mosq/EiEjh;8c\ssqA3Nu_Q (d0, q1, r0, m1, '/2/jeg', ... (4 bytes))
1432571555: Sending PUBACK to mosq/EiEjh;8c\ssqA3Nu_Q (Mid: 1)
1432571555: Sending PUBLISH to lens_kPWHtQiFUMTz2h4fbBfma4gxR0p (d0, q0, r0, m0, '/2/jeg', ... (4 bytes))
1432571557: Received DISCONNECT from mosq/EiEjh;8c\ssqA3Nu_Q
1432571557: Client mosq/EiEjh;8c\ssqA3Nu_Q disconnected.
1432571576: New connection from 192.168.0.29 on port 1883.
1432571576: New client connected from 192.168.0.29 as mosq/`JSMd1Yi0Ag_>S6iEG (c1, k5).
1432571576: Sending CONNACK to mosq/`JSMd1Yi0Ag_>S6iEG (0, 0)
1432571576: Received PUBLISH from mosq/`JSMd1Yi0Ag_>S6iEG (d0, q1, r1, m1, '/2/jeg', ... (4 bytes))
1432571576: Sending PUBACK to mosq/`JSMd1Yi0Ag_>S6iEG (Mid: 1)
1432571576: Sending PUBLISH to lens_kPWHtQiFUMTz2h4fbBfma4gxR0p (d0, q0, r0, m0, '/2/jeg', ... (4 bytes))
1432571578: Received DISCONNECT from mosq/`JSMd1Yi0Ag_>S6iEG
1432571578: Client mosq/`JSMd1Yi0Ag_>S6iEG disconnected.
1432571594: New connection from 192.168.0.29 on port 1883.
1432571594: New client connected from 192.168.0.29 as mosq/_aErGr<8WU]@^Iw:^S (c1, k5).
1432571594: Sending CONNACK to mosq/_aErGr<8WU]@^Iw:^S (0, 0)
1432571594: Received PUBLISH from mosq/_aErGr<8WU]@^Iw:^S (d0, q1, r1, m1, '/2/jeg', ... (4 bytes))
1432571594: Sending PUBACK to mosq/_aErGr<8WU]@^Iw:^S (Mid: 1)
1432571594: Sending PUBLISH to lens_kPWHtQiFUMTz2h4fbBfma4gxR0p (d0, q0, r0, m0, '/2/jeg', ... (4 bytes))
1432571596: Received DISCONNECT from mosq/_aErGr<8WU]@^Iw:^S
1432571596: Client mosq/_aErGr<8WU]@^Iw:^S disconnected.
```

**Comment by mgdm** [comment]
I've not had a chance to look into this yet, but I'll try to this evening.

**Comment by Shemeikka** [comment]
I can confirm that publishing using QoS level 2 doesn't work. I don't have logs to paste but levels 0 and 1 work just fine.

I'm using
PHP 5.4.45-0+deb7u1
mosquitto version 1.4.2 
Newest mosquitto-php client from pecl

**Comment by cid2610** [comment]
Yes, me too, I can't publish with QoS = 2

**Comment by mgdm** [comment]
I imagine it's because you're not looping long enough (or at all) after you've published. MQTT has a lot of round trips, which means it needs to wait for confirmation messages when it connects, subscribes, and publishes. With QoS=2, there is another round trip required. You must call either `Mosquitto\Client::loop()` a number of times, or `Mosquitto\Client::loopForever()` to let the library handle the messages in its queues. It's also a good idea to use the callback functions to ensure you only try to publish after the client has managed to connect.

For example, this works fine:

```php
<?php

$c = new Mosquitto\Client;
$c->onConnect(function() use ($c) {
    $c->publish('mgdm/test', 'Hello', 2);
});

$c->connect('test.mosquitto.org');

for ($i = 0; $i < 100; $i++) {
    // Loop around to permit the library to do its work
    $c->loop(1);
}

echo "Finished\n";
```

**Comment by sthaimor** [comment]
Cant publish a Mesage with QOS = 2:
`$CLIENT = new Mosquitto\Client("Heizungssteuerung");
$CLIENT->onConnect(function() use ($CLIENT, $SERIAL)
{
    $CLIENT->publish("$SERIAL/Config", "LOCATE", 2);
    $CLIENT->disconnect();
});
$CLIENT->connect("localhost");
$CLIENT->loopForever();
`

**Comment by sthaimor** [comment]
This code doesn't work:
`$CLIENT = new Mosquitto\Client("PHP");`
`$CLIENT->onConnect(function() use ($CLIENT, $SERIAL)`
`{`
`$CLIENT->publish("$SERIAL/Config", "LOCATE", 2);`
`$CLIENT->disconnect();`
`});`
`$CLIENT->connect("localhost");`
`$CLIENT->loopForever();`
