### ISSUE TITLE
a problem on publish with http request

### ISSUE THREAD

**Issue by acrazing** [mgdm/Mosquitto-PHP#28]
when i do stress test with mine website, i use a iteration as follow to publish message:

```
/**
 * @file web-pub.php
 */

$client = new Mosquitto\Client(uniqid());
$client->connect('server.mosquitto', 1883, 60);
for($i = 0; $i < 1000; $i++) {
    $client->publish('/test/stress', 'message stress test '.$i);
}
```

and then I use  http_load to send 100 request to the server, If working properly, i will receive 100000 messages in test client, but, in actually, I only can receive about 70000 messages, about 30k messages is lost.

i guess the method Mosquitto\Client::publish created a thread to send message to the broker, and if the message inflight queue is long enough, the PHP process finished processing the request and then exit without waiting for the socket thread finishing work.

this will cause message lose in high concurrent server!

**Comment by mgdm** [comment]
It doesn't create any threads, but in order to process the message queues, you need to call `$client->loop()` periodically to let the underlying library do what it needs to do. You could call it once every 10 message publishes or so, which would probably be enough (though I've not tested).
