### ISSUE TITLE
Cannot Use class files with my existing project

### ISSUE THREAD

**Issue by TNChalise** [mgdm/Mosquitto-PHP#33]
I have done with all installation prerequisites. I have now currently loaded`mosquitto.so` extension in my `php.ini`. But, I can use:
`$client = new \Mosquitto\Client();`
But cant:
`$base   = new \EventBase();`
Is there anything, I have to do to remove fatal error of 

> Class 'EventBase' not found.

Any help will be appreciated.
![extension](https://cloud.githubusercontent.com/assets/4486063/14099827/7d2941a6-f5a8-11e5-931a-9d858115c22c.png)

I have executed in cli mode.

**Comment by saurabh-diffion** [comment]
You need to install php libevent extension using pecl to use EventBase.
This extension is however not compatible with php 7.
