### ISSUE TITLE
Installing Mosquitto-Alpha

### ISSUE THREAD

**Issue by davidScotcomms** [mgdm/Mosquitto-PHP#35]
I'm trying to install Mosquito-alpha in order to run your library to connect to a Mosquitto server running on a different machine.  It throws a `make` failed error when installing on ubuntu and can't really progress beyond this.

I've tried installing 'libmosquitto-dev' but this doesn't exist on the Ubuntu repository.  There is however 'libmosquitto0-dev' which I have got installed.

I'm running PHP version 5.5.9 and have PECL installed.

Any advice or help would be appreciated.  I would really like to get this running. :)

This is a copy of the install with the error thrown
[Mosquitto Alpha Install Log.txt](https://github.com/mgdm/Mosquitto-PHP/files/218857/Mosquitto.Alpha.Install.Log.txt)

**Comment by mgdm** [comment]
Hi
Could you try removing the `libmosquitto-*` libraries you've got installed, and install the versions from this PPA instead? It sounds like you're running on an old version.

https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa/

**Comment by davidScotcomms** [comment]
Ah thanks that seems to have done the trick!  Got it all working now!
