### ISSUE TITLE
Unable to load mosquitto.so undefined symbol: executor_globals in Unknown on line 0

### ISSUE THREAD

**Issue by JHChan314** [mgdm/Mosquitto-PHP#36]
Dear all,
I am using CentOS 7, Apache 2.4, PHP 5.6, and install Mosquitto-PHP via `pecl` command and config php.ini to load mosquitto library, then I run `php` command, I got below message:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mosquitto.so' - /usr/lib64/php/modules/mosquitto.so: undefined symbol: executor_globals in Unknown on line 0

I am use absolute path to include mosquitto library, I can't find any message about this warning.
Do anyone have same issue? How to resolve it? 

Thanks.

**Comment by serverglen** [comment]
are you fix?
