### ISSUE TITLE
Error on installing extension

### ISSUE THREAD

**Issue by justwakku** [mgdm/Mosquitto-PHP#37]
I got this error when running `make` command. I use PHP7. Is there a test version for PHP7?

> $ phpize
> Configuring for:
> PHP Api Version:         20151012
> Zend Module Api No:      20151012
> Zend Extension Api No:   320151012
> 
> $ ./configure --with-mosquitto=/usr/mosquitto
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking for C compiler default output file name... a.out
> checking whether the C compiler works... yes
> checking whether we are cross compiling... no
> checking for suffix of executables...
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /usr/php
> checking for PHP includes... -I/usr/php/include/php -I/usr/php/include/php/main -I/usr/php/include/php/TSRM -I/usr/php/include/php/Zend -I/usr/php/include/php/ext -I/usr/php/include/php/ext/date/lib
> checking for PHP extension directory... /usr/php/lib/php/extensions/no-debug-non-zts-20151012
> checking for PHP installed headers prefix... /usr/php/include/php
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... no
> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
> checking for gawk... gawk
> checking for mosquitto support... yes, shared
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking whether strerror_r is declared... yes
> checking for strerror_r... yes
> checking whether strerror_r returns char *... no
> checking for ld used by cc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for /usr/bin/ld option to reload object files... -r
> checking for BSD-compatible nm... /usr/bin/nm -B
> checking whether ln -s works... yes
> checking how to recognize dependent libraries... pass_all
> checking dlfcn.h usability... yes
> checking dlfcn.h presence... yes
> checking for dlfcn.h... yes
> checking the maximum length of command line arguments... 1966080
> checking command to parse /usr/bin/nm -B output from cc object... ok
> checking for objdir... .libs
> checking for ar... ar
> checking for ranlib... ranlib
> checking for strip... strip
> checking if cc supports -fno-rtti -fno-exceptions... no
> checking for cc option to produce PIC... -fPIC
> checking if cc PIC flag -fPIC works... yes
> checking if cc static flag -static works... no
> checking if cc supports -c -o file.o... yes
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> 
> creating libtool
> appending configuration tag "CXX" to libtool
> configure: creating ./config.status
> config.status: creating config.h
> 
> $ make
> /bin/sh /src/Mosquitto-PHP/libtool --mode=compile cc  -I. -I/src/Mosquitto-PHP -DPHP_ATOM_INC -I/src/Mosquitto-PHP/include -I/src/Mosquitto-PHP/main -I/src/Mosquitto-PHP -I/usr/php/include/php -I/usr/php/include/php/main -I/usr/php/include/php/TSRM -I/usr/php/include/php/Zend -I/usr/php/include/php/ext -I/usr/php/include/php/ext/date/lib -I/usr/mosquitto/include  -DHAVE_CONFIG_H  -g -O2   -c /src/Mosquitto-PHP/mosquitto.c -o mosquitto.lo
> mkdir .libs
>  cc -I. -I/src/Mosquitto-PHP -DPHP_ATOM_INC -I/src/Mosquitto-PHP/include -I/src/Mosquitto-PHP/main -I/src/Mosquitto-PHP -I/usr/php/include/php -I/usr/php/include/php/main -I/usr/php/include/php/TSRM -I/usr/php/include/php/Zend -I/usr/php/include/php/ext -I/usr/php/include/php/ext/date/lib -I/usr/mosquitto/include -DHAVE_CONFIG_H -g -O2 -c /src/Mosquitto-PHP/mosquitto.c  -fPIC -DPIC -o .libs/mosquitto.o
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client___construct’:
> /src/Mosquitto-PHP/mosquitto.c:114: warning: cast to pointer from integer of different size
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_setTlsCertificates’:
> /src/Mosquitto-PHP/mosquitto.c:159: warning: cast to pointer from integer of different size
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_setTlsInsecure’:
> /src/Mosquitto-PHP/mosquitto.c:195: warning: cast to pointer from integer of different size
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_setTlsOptions’:
> /src/Mosquitto-PHP/mosquitto.c:222: warning: cast to pointer from integer of different size
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_setTlsPSK’:
> /src/Mosquitto-PHP/mosquitto.c:247: warning: cast to pointer from integer of different size
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onConnect’:
> /src/Mosquitto-PHP/mosquitto.c:421: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval _’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:423: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:424: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onDisconnect’:
> /src/Mosquitto-PHP/mosquitto.c:455: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:457: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:458: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onLog’:
> /src/Mosquitto-PHP/mosquitto.c:489: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:491: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:492: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onSubscribe’:
> /src/Mosquitto-PHP/mosquitto.c:523: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:525: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:526: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onUnsubscribe’:
> /src/Mosquitto-PHP/mosquitto.c:557: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:559: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:560: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onMessage’:
> /src/Mosquitto-PHP/mosquitto.c:591: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:593: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:594: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zim_Mosquitto_Client_onPublish’:
> /src/Mosquitto-PHP/mosquitto.c:625: error: incompatible type for argument 1 of ‘zval_addref_p’
> /usr/php/include/php/Zend/zend_types.h:820: note: expected ‘struct zval *’ but argument is of type ‘zval’
> /src/Mosquitto-PHP/mosquitto.c:627: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:628: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘mosquitto_client_object_get’:
> /src/Mosquitto-PHP/mosquitto.c:862: warning: initialization makes pointer from integer without a cast
> /src/Mosquitto-PHP/mosquitto.c: In function ‘mosquitto_client_object_destroy’:
> /src/Mosquitto-PHP/mosquitto.c:884: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:884: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:885: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:885: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:886: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:886: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:887: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:887: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:888: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:888: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:889: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:889: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:890: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c:890: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
> /src/Mosquitto-PHP/mosquitto.c: At top level:
> /src/Mosquitto-PHP/mosquitto.c:900: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘mosquitto_client_object_new’
> /src/Mosquitto-PHP/mosquitto.c:967:56: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_connect_callback’:
> /src/Mosquitto-PHP/mosquitto.c:967: error: ‘ZVAL_STRINGL’ undeclared (first use in this function)
> /src/Mosquitto-PHP/mosquitto.c:967: error: (Each undeclared identifier is reported only once
> /src/Mosquitto-PHP/mosquitto.c:967: error: for each function it appears in.)
> /src/Mosquitto-PHP/mosquitto.c:970: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:972: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:976: error: invalid type argument of ‘unary *’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:980: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:981: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:984: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_disconnect_callback’:
> /src/Mosquitto-PHP/mosquitto.c:1005: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:1007: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:1011: error: invalid type argument of ‘unary _’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:1015: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1018: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1039:44: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_log_callback’:
> /src/Mosquitto-PHP/mosquitto.c:1039: error: ‘ZVAL_STRINGL’ undeclared (first use in this function)
> /src/Mosquitto-PHP/mosquitto.c:1044: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:1046: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:1050: error: invalid type argument of ‘unary _’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:1054: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1055: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1058: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_message_callback’:
> /src/Mosquitto-PHP/mosquitto.c:1078: warning: cast to pointer from integer of different size
> /src/Mosquitto-PHP/mosquitto.c:1082: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:1084: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:1088: error: invalid type argument of ‘unary _’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:1092: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1095: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_publish_callback’:
> /src/Mosquitto-PHP/mosquitto.c:1118: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:1120: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:1124: error: invalid type argument of ‘unary _’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:1128: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1131: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_subscribe_callback’:
> /src/Mosquitto-PHP/mosquitto.c:1161: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:1163: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:1167: error: invalid type argument of ‘unary _’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:1171: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1172: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1173: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1176: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘php_mosquitto_unsubscribe_callback’:
> /src/Mosquitto-PHP/mosquitto.c:1198: warning: assignment from incompatible pointer type
> /src/Mosquitto-PHP/mosquitto.c:1200: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
> /src/Mosquitto-PHP/mosquitto.c:1204: error: invalid type argument of ‘unary _’ (have ‘zval’)
> /src/Mosquitto-PHP/mosquitto.c:1208: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c:1211: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
> /usr/php/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval _’ but argument is of type ‘struct zval *_’
> /src/Mosquitto-PHP/mosquitto.c: In function ‘zm_startup_mosquitto’:
> /src/Mosquitto-PHP/mosquitto.c:1302: error: too many arguments to function ‘zend_register_internal_class_ex’
> /src/Mosquitto-PHP/mosquitto.c:1303: error: ‘mosquitto_client_object_new’ undeclared (first use in this function)
> /src/Mosquitto-PHP/mosquitto.c:1307: error: too many arguments to function ‘zend_register_internal_class_ex’
> make: **\* [mosquitto.lo] Error 1

**Comment by mgdm** [comment]
Hi,
I've not had a lot of time to work on the PHP 7 port yet, though I have started it. I'll have a look in the next few days to see if I can get through it.
