### ISSUE TITLE
PHP Composer support? 

### ISSUE THREAD

**Issue by glynhudson** [mgdm/Mosquitto-PHP#41]
Love the project. Would it be possible to add a `composer.json` file and [publish to Composer package list](https://packagist.org/) to allow this  install via Composer? 

E.g. https://github.com/bluerhinos/phpMQTT/blob/master/composer.json

**Comment by mgdm** [comment]
Unfortunately not - as this is a PECL extension, composer can't install it. You can currently use `composer.json` to require that a PECL extension is present but you can't use it to install them yet. There is an open PR for that so if it is merged and I need to do anything to support it, I will.

https://github.com/composer/composer/pull/2898

**Comment by glynhudson** [comment]
Ah ok. Maybe Pickle will help...in the future. It looks like it's currently in development:

https://github.com/FriendsOfPHP/pickle
