### ISSUE TITLE
PHP 7 Segmentation Fault

### ISSUE THREAD

**Issue by ThomasTacquet** [mgdm/Mosquitto-PHP#53]
Hi.

I noticed that if I compile Mosquitto-PHP under a PHP 7.0 environment, some random bugs occur when running example scripts.

When I create a basic subscriber, the php script randomly crash `segmentation fault`. I used example scripts and tested to fix em without success.

I tested both cases under clean Debian 9 installations.

But under a full PHP5.6 environnement, everything works fine, with libmosquittlo-dev 1.4.3. Mosquitto-php seems not compliant with PHP7.

**Comment by argakon** [comment]
Hi, i found this segfault too and probably i fixed him in pull request #54 
Would be great if you can test it.

**Comment by ThomasTacquet** [comment]
I tested your pull request under the same environement, compiled with PHP7 clean install and looks fine !
I don't have anymore problems with segementation fauls :+1:
