### ISSUE TITLE
when the epcl package is updated?

### ISSUE THREAD

**Issue by FoujanetG** [mgdm/Mosquitto-PHP#57]
Hi all,

I see on the Issues a lot of bugs with theirs solution.
Do you know when the package pecl on linux is updated to have all bug fixes?

thanks a lot for your work!
GF

**Comment by mgdm** [comment]
I intend to update it once I complete the changes to handle auto reconnection in `loopForever()` - I can't use the underlying libary's version of it because it doesn't let PHP handle exceptions while the loop is running. Once that's done, the extension should be feature complete for a release.
