### ISSUE TITLE
PHPStorm stubs

### ISSUE THREAD

**Issue by ReSpawN** [mgdm/Mosquitto-PHP#64]
I haven't been able to get them working without more info, so officially requesting PHPStorm compatible stubs. :)

Raw source: https://github.com/JetBrains/phpstorm-stubs

**Comment by ReSpawN** [comment]
Crap, I found it just as I submitted the ticket.
https://github.com/Nakard/mosquitto-stub/tree/master

I'll report back if it seems insufficient.

**Comment by mgdm** [comment]
Oh, cool, I had no idea those existed! Thanks!

**Comment by mgdm** [comment]
React had been on my list of things to look at, but I've not had time unfortunately. I'd be interested to hear how you get on though.

**Comment by ReSpawN** [comment]
I'll keep you up to date and if I got a working example I'll push it to the examples for you to take a look at. Note that EventLoop still relies on LibEvEvent or any same event handler.
