### ISSUE TITLE
zend_mm_head with PHP - ZTS

### ISSUE THREAD

**Issue by rugbymauri** [mgdm/Mosquitto-PHP#65]
Hello

if i complie php with the option --enable-maintainer-zts, the Mosquitto-PHP Module is not working.
all Mosquitto-PHP test fails. 

```

=====================================================================
PHP         : /usr/local/php/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.1.1
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux myhost 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l
INI actual  : /home/pi/var/Mosquitto-PHP/tmp-php.ini
More .INIs  :   
.....

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   49
---------------------------------------------------------------------

Number of tests :   29                29
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   26 ( 89.7%) ( 89.7%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    3 ( 10.3%) ( 10.3%)
---------------------------------------------------------------------
Time taken      :   11 seconds
=====================================================================

```

I get a "zend_mm_head corrupted" message if I run the test manually.

```
~/var/Mosquitto-PHP/tests$ php Client/__construct.php
object(Mosquitto\Client)#1 (0) {
}
zend_mm_heap corrupted

```

```
~/var/Mosquitto-PHP$ export USE_ZEND_ALLOC=0
~/var/Mosquitto-PHP$ php tests/Client/clearWill.php
Caught Mosquitto\Exception with code 0 and message: Mosquitto\Client::clearWill() expects exactly 0 parameters, 1 given
*** Error in `php': free(): invalid pointer: 0x76689714 ***
Aborted

```

PHP without ZTS work fine.

**Comment by mgdm** [comment]
Hi, could you try again with the current `master` branch? I think it may now be fixed.

**Comment by rugbymauri** [comment]
Works fine!

i'm gonna now install the extension and test it with the application

thanks!!

`=====================================================================
PHP         : /usr/local/php/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.1.1
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux s5fu1az9p 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l
INI actual  : /root/Mosquitto-PHP/tmp-php.ini
More .INIs  :   
---------------------------------------------------------------------
PHP         : /usr/local/php/bin/phpdbg 
PHP_SAPI    : phpdbg
PHP_VERSION : 7.1.1
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux myhost 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l
INI actual  : /root/Mosquitto-PHP/tmp-php.ini
More .INIs  : 
---------------------------------------------------------------------
CWD         : /root/Mosquitto-PHP
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2017-03-16 08:34:35
=====================================================================
PASS Mosquitto\Client::__construct() [tests/Client/__construct.phpt] 
PASS Mosquitto\Client::setWill() [tests/Client/clearWill.phpt] 
PASS Mosquitto\Client::connect() [tests/Client/connect.phpt] 
PASS Mosquitto\Client::disconnect() [tests/Client/disconnect.phpt] 
PASS Mosquitto\Client::exitLoop() [tests/Client/exitLoop.phpt] 
PASS Mosquitto\Client::getSocket() [tests/Client/getSocket.phpt] 
PASS Mosquitto\Client::loop() [tests/Client/loop.phpt] 
PASS Mosquitto\Client::loopForever() [tests/Client/loopForever.phpt] 
PASS Mosquitto\Client::onConnect() [tests/Client/onConnect.phpt] 
PASS Mosquitto\Client::onDisconnect() [tests/Client/onDisconnect.phpt] 
PASS Mosquitto\Client::onLog() [tests/Client/onLog.phpt] 
PASS Mosquitto\Client::onMessage() [tests/Client/onMessage.phpt] 
PASS Mosquitto\Client::onSubscribe() [tests/Client/onSubscribe.phpt] 
PASS Mosquitto\Client::onUnsubscribe() [tests/Client/onUnsubscribe.phpt] 
PASS Mosquitto\Client::publish() [tests/Client/publish.phpt] 
PASS Mosquitto\Client::setCredentials() [tests/Client/setCredentials.phpt] 
PASS Mosquitto\Client::setMaxInFlightMessages() [tests/Client/setMaxInFlightMessages.phpt] 
PASS Mosquitto\Client::setMessageRetry() [tests/Client/setMessageRetry.phpt] 
PASS Mosquitto\Client::setReconnectDelay() [tests/Client/setReconnectDelay.phpt] 
FAIL Mosquitto\Client::setTlsCertificates() [tests/Client/setTlsCertificates.phpt] 
PASS Mosquitto\Client::setTlsInsecure() [tests/Client/setTlsInsecure.phpt] 
PASS Mosquitto\Client::setTlsOptions() [tests/Client/setTlsOptions.phpt] 
FAIL Mosquitto\Client::setTlsPSK() [tests/Client/setTlsPSK.phpt] 
PASS Mosquitto\Client::setWill() [tests/Client/setWill.phpt] 
PASS Mosquitto\Client::subscribe() [tests/Client/subscribe.phpt] 
PASS Mosquitto\Client::unsubscribe() [tests/Client/unsubscribe.phpt] 
PASS Mosquitto\Message::__construct() [tests/Message/__construct.phpt] 
PASS Mosquitto\Message::tokeniseTopic() [tests/Message/tokeniseTopic.phpt] 
PASS Mosquitto\Message::topicMatchesSub() [tests/Message/topicMatchesSub.phpt] 
=====================================================================
TIME END 2017-03-16 08:36:07

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   49
---------------------------------------------------------------------

Number of tests :   29                29
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    2 (  6.9%) (  6.9%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   27 ( 93.1%) ( 93.1%)
---------------------------------------------------------------------
Time taken      :   92 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Mosquitto\Client::setTlsCertificates() [tests/Client/setTlsCertificates.phpt]
Mosquitto\Client::setTlsPSK() [tests/Client/setTlsPSK.phpt]
=====================================================================

`
