### ISSUE TITLE
disconnect response code 7

### ISSUE THREAD

**Issue by jhaoheng** [mgdm/Mosquitto-PHP#66]
Hi 

I got a problem about code = 7.

I use `$client->loopForever(3600);`
But mqtt still disconnect and the response code is 7

What is the meaning about 7 of broker?

Thank you

**Comment by jhaoheng** [comment]
I guess i solve this question.

i set a small keep-alive number. And NOT happen until now.

**Comment by wangsheng** [comment]
@jhaoheng I met the same problem. Can you tell me what number you set for the keep-alive ? 

Thank you.

**Comment by jhaoheng** [comment]
@wangsheng 
Hi , i forgot that , but now my config is 

```
   $broker     = $config->mqtt->broker;
    $port       = $config->mqtt->port;
    $username   = $config->mqtt->username;
    $password   = $config->mqtt->password;
    $clientId   = '';
    $Qos        = 2;

    $client = new Mosquitto\Client($clientId);
    $client->setCredentials($username, $password);
    $client->connect($broker, $port, 20);
    $client->onConnect('connect');
    $client->onDisconnect('disconnect');
    $client->onSubscribe('subscribe');
    $client->onMessage('message');
    $client->subscribe($topic, $Qos); 

    while (true) {
        $client->loop();
        if ($GLOBALS['loopbreak']) {
            break;
        }
    }
```

**Comment by WeeSee** [comment]
What is reason 7 ?

What was the solution before this issue got closed?

When I catch the error, it gives

    The connection was lost

What's going wrong here?

**Comment by WeeSee** [comment]
solved: I had a second subscriber running with the same mqtt-client-id.
