### ISSUE TITLE
Option to set the version of the MQTT protocol

### ISSUE THREAD

**Issue by mattsches** [mgdm/Mosquitto-PHP#67]
When using `mosquitto_pub` (1.4.8) on the command line, there is an option to set the protocol version

> -V : specify the version of the MQTT protocol to use when connecting.
      Can be mqttv31 or mqttv311. Defaults to mqttv31.

I suppose `Mosquitto-PHP` makes use of the default protocol version and there is no way to set the version in the client code? Unfortunately my broker (Home Assistant built-in broker) requires `mqttv311` :(

Will now try to set up my own custom broker using `Mosquitto` and integrate it into my Home Assistant setup, but it would be nice to be able to set the version in my client script.

EDIT: It's working now, but please consider introducing the protocol option anyway …

**Comment by mgdm** [comment]
I didn't realise that was possible, though I've just had a look into the library code and can see how it's done now:

https://github.com/eclipse/mosquitto/blob/master/lib/mosquitto.h#L947

 I'll give it a go in the next couple of days, I don't have a lot of time right at this moment.

**Comment by mattsches** [comment]
Thanks, no hurry! I got it to work by configuring the broker to accept 3.1.

**Comment by mgdm** [comment]
Hi, I've had a go at it now, can you give the patch in https://github.com/mgdm/Mosquitto-PHP/pull/68 a go and let me know how you get on?

**Comment by mattsches** [comment]
Finally found the time to check out your branch and test it against the embedded MQTT broker of Home Assistant.

I can confirm that setting the protocol works, and that it makes a difference on the broker side.

The following does NOT work against the broker:
```php
$c = new \Mosquitto\Client();
$c->setProtocolVersion(\Mosquitto\ProtocolVersion::V31);
...
```
while this works:
```php
$c = new \Mosquitto\Client();
$c->setProtocolVersion(\Mosquitto\ProtocolVersion::V311);
...
```

To sum it up: Your patch works as expected :smile:
