### ISSUE TITLE
Correlate log level integer to string

### ISSUE THREAD

**Issue by kodekraft** [mgdm/Mosquitto-PHP#71]
I looked through the documentation and the source code, and I can't figure out what the integer representation of the following constants referenced in your documentation:

```
constant LOG_DEBUG
Identifies a debug-level log message

constant LOG_INFO
Identifies an info-level log message

constant LOG_NOTICE
Identifies a notice-level log message

constant LOG_WARNING
Identifies a warning-level log message

constant LOG_ERR
Identifies an error-level log message
```

In essence, when a level of 16 is returned, does that mean LOG_DEBUG?

It does not appear that you're following PSR-3 for logging which is based off [RFC-5424](https://tools.ietf.org/html/rfc5424). If you were, the numerical coding for your log types would be as they're described on page 11:
```

           Numerical         Severity
             Code

              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages
```

**Comment by mgdm** [comment]
Those are Mosquitto's own internal error codes, which I believe are all powers of two, as I didn't want to make assumptions about how people were going to use them. You're correct in that LOG_DEBUG is 16:

```
% php -r 'var_dump(Mosquitto\Client::LOG_DEBUG);'
Command line code:1:
int(16)
```

I'll look at adding them to the docs.
