### ISSUE TITLE
About setTlsCertificates

### ISSUE THREAD

**Issue by ayzen1988** [mgdm/Mosquitto-PHP#75]
please help me how to solve the problem.

function push_msg($target, $message) {
    try {
        $client = new Mosquitto\Client();
		$client->setTlsCertificates('/etc/mosquitto/client/ca.crt', '/etc/mosquitto/client/client.crt', '/etc/mosquitto/client/client.key');
		$client->onConnect(function() use ($client) {
			echo "Connected successfully\n";
			$client->disconnect();
		});
		$client->connect('192.168.1.168', 1883);
		$client->loopForever();
		unset($client);
    } catch (Mosquitto\Exception $ex) {
		var_dump($ex->getMessage());
    }
}

execute function -> push_msg('test', date('Y-m-d H:i:s'));
**catch Exception "A TLS error occurred."**

mosquitto error msg.
**1504840227: New connection from 192.168.1.168 on port 1883.
1504840227: OpenSSL Error: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
1504840227: OpenSSL Error: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure
1504840227: Socket error on client <unknown>, disconnecting.**

But.
The following instructions can be used.
**mosquitto_sub -t test --cafile /etc/mosquitto/client/ca.crt --cert /etc/mosquitto/client/client.crt --key /etc/mosquitto/client/client.key --insecure**

**Comment by crashev** [comment]
I would ask couple questions first:
- is port 1883 SSL port? SSL usually is set on port 8883
- also I found that when using mosquitto_pub/sub tools you always have to type host that is in Common Name of generated SSL certificate in order for this to work

**Comment by ayzen1988** [comment]
1.is port 1883 SSL port.
2.How can I solve it？

**Comment by ayzen1988** [comment]
Add the following code.
**$client->setTlsInsecure(true);**
I have solved it.

Thank you.
