### ISSUE TITLE
Not able to load mosquitto.so in Zend Server

### ISSUE THREAD

**Issue by arshadwis** [mgdm/Mosquitto-PHP#79]
Hi,not able to intialize mosquitto.so in zend server php 7.1
Getting error like this.

Startup: mosquitto: Unable to initialize moduleModule compiled with module API=20151012PHP    compiled with module API=20160303These options need to match in Unknown on line 0

Enviornment Setup
-------------------------

Aws Ubuntu 16 With Zend Server 9.1.1,Php 7.1

**Comment by mgdm** [comment]
Hello,
It looks like you've compiled your Mosquitto-PHP against a different version of PHP from what you're loading it into. I guess you might need to do rebuild it from source, doing something like this:

```bash
./configure --with-php-config=/path/to/zend-server/bin/php-config
make
make install
```
