### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Mosquitto\Client' not found

### ISSUE THREAD

**Issue by maneeshtiwari007** [mgdm/Mosquitto-PHP#80]
i am not able to run that script please check and let me know please
Fatal error: Uncaught Error: Class 'Mosquitto\Client' not found in /var/www/html/Mosquitto-PHP-master/examples/test.php:4 Stack trace: #0 {main} thrown in /var/www/html/Mosquitto-PHP-master/examples/test.php on line 4

**Comment by tuyashequ** [comment]
use \Mosquitto\Client to replace Mosquitto\Client and try again

**Comment by hitswa** [comment]
nop not working

**Comment by xtrasmal** [comment]
Same here. I probably did not configure my php correctly.
In the CLI it can find `Mosquitto\Client`, but within the application it can not.

**Comment by xtrasmal** [comment]
Shit.. I can dump the class methods, but PHP storm says class not found!! PRETTY SAD

**Comment by Renslmf23** [comment]
(Sorry for stealing your thread, but I think this is better than opening a new one)
I have the same problem. Loading the php via the console works, but using the webpage it gives me this error. Also, according to this little script `
<?php
if (!extension_loaded('Mosquitto-php')) {
  echo "Mosquitto not loaded";
} else {
  echo "Mosquitto loaded";
}
?>
` the extension is not loaded. I do not know what to do now, how do I verify that I installed the plugin the correct way?

**Comment by mgdm** [comment]
The extension is called just `mosquitto`, not `mosquitto-php`.

**Comment by sharkyy** [comment]
Hi Guys,

I have the same issue with 
`PHP Fatal error:  Uncaught Error: Class 'Mosquitto\\Client' not found in `

This is what I tried to call:
`use Mosquitto\Client;

//Variables
	$host = "localhost";
	$port = 1883;
	$username = 'username;
	$password = 'password';
	
	$responseClient = new Mosquitto\Client("PHP");
	$responseClient->setCredentials($username, $password);
	//connect to the Broker
	$responseClient->connect($host, $port);`

Is there any solution for this problem?
Strange thing I've already noticed is the double backslash in the error message.

Best
Max

**Comment by tuyashequ** [comment]
add an ‘\’ before Mosquitto\Client() is useful like :$responseClient = new \Mosquitto\Client("PHP”); try it~


原始邮件
发件人:sharkyynotifications@github.com
收件人:mgdm/Mosquitto-PHPMosquitto-PHP@noreply.github.com
抄送:tuyashequtuyashequ@163.com; Commentcomment@noreply.github.com
发送时间:2019年6月23日(周日) 15:44
主题:Re: [mgdm/Mosquitto-PHP] Fatal error: Uncaught Error: Class'Mosquitto\Client' not found (#80)


Hi Guys,
I have the same issue with
 PHP Fatal error: Uncaught Error: Class 'Mosquitto\\Client' not found in
This is what I tried to call:
 `use Mosquitto\Client;
//Variables
 $host = "localhost";
 $port = 1883;
 $username = 'username;
 $password = 'password';
$responseClient = new Mosquitto\Client("PHP"); $responseClient-setCredentials($username, $password); //connect to the Broker $responseClient-connect($host, $port);`
Is there any solution for this problem?
 Strange thing I've already noticed is the double backslash in the error message.
Best
 Max

**Comment by AndreasPercher** [comment]
Hello,
is there a sollution?
I can do it from command line (even without "use Mosquitto\Client;" and/or the \  in new \Mosquitto\Client), but not by webserver.
It works until I installed pi-hole this days...

```
use Mosquitto\Client;

function sendMQTT($topic,$payload) {
$user = "****";
$pwd  = "***";
	
if (!extension_loaded('Mosquitto')) {
  echo "Mosquitto not loaded\n";
} else {
  // echo "Mosquitto loaded\n";
}
  try {
    $client = new \Mosquitto\Client("hausautomation");
  	$client->connect("localhost", 1883, 60);
  	$count=0;
 	$count++;
       $client->setCredentials($user,$pwd);
 	$client->publish($topic,$payload, 0, false);
	$client->loop();
	echo "OK";
  } catch ( \Exception $e) {
    $erg = 'Exception abgefangen: '. $e->getMessage()."\n";
    echo $erg;
    error_log($erg,3,"/var/www/html_err.log");
    throw $e;
  }
}
```

Any Tip will be helpfull.

**Comment by alesinicio** [comment]
Guessing you have different `php.ini` loaded in CLI and webserver. Probably you are not loading the Mosquitto extension on the webserver. Check with `phpinfo()`.

Also, your `if` statement does not abort execution nor instantiation of the Mosquitto client if the check for the extension fails -- probably you should handle this scenario in some graceful way.
