### ISSUE TITLE
Connection Refuse when using loop or loopForever() function.

### ISSUE THREAD

**Issue by manektechyagnik** [mgdm/Mosquitto-PHP#87]
I had install mosquito successfully on my server. and change the php.ini as well as.
also check extension is loaded or not.
but when i had try to run script from putty. i got error. which code i had use loop and loopForever function.
i try to find solution but didn't get anything.
System : PHP 7 Ubuntu 0.16.
below are my code. please have a look.
```
<?php

$client = new Mosquitto\Client();
$client->onConnect('connect');
$client->onDisconnect('disconnect');
$client->onSubscribe('subscribe');
$client->onMessage('message');
$client->connect('My public ip', 1883, 60);
$client->subscribe('/#', 1);


while (true) {
    $client->loop();
    sleep(2);
}

$client->disconnect();
unset($client);

function connect($r) {
    echo "I got code {$r}\n";
}

function subscribe() {
    echo "Subscribed to a topic\n";
}

function message($message) {
    printf("\nGot a message on topic %s with payload:%s", $message->topic, $message->payload);
}

function disconnect() {
    echo "Disconnected cleanly\n";
}
```
**Output :** 
ubuntu@ip-XXX-Xx-XX-XXX:/var/www/html$ php pub.php
I got code 5
Disconnected cleanly
PHP Fatal error:  Uncaught Mosquitto\Exception: The connection was refused. in /var/www/html/pub.php:13
Stack trace:
#0 /var/www/html/pub.php(13): Mosquitto\Client->loop()
#1 {main}
  thrown in /var/www/html/pub.php on line 13

**Comment by Bunkerschild** [comment]
You did not set the CLIENT ID with class constructor. Based on the brokers configuration, it could be possible to accept only specific client prefixes. If the client doesn't sent one or is not sending the expected prefix, the connection will fail as described.
