### ISSUE TITLE
Publish with QoS 2 doesn't work

### ISSUE THREAD

**Issue by x0tester0x** [mgdm/Mosquitto-PHP#95]
Why does this code not work? The same code is in the examples...
`$CLIENT = new Mosquitto\Client("PHP");`
`$CLIENT->onConnect(function() use ($CLIENT, $SERIAL)`
`{`
`$CLIENT->publish("$SERIAL/Config", "LOCATE", 2);`
`$CLIENT->disconnect();`
`});`
`$CLIENT->connect("localhost");`
`$CLIENT->loopForever();`

**Comment by mgdm** [comment]
Sorry, I just realised that code is broken. The proper one should look more like that below. I'll update the README shortly. Note that I'm storing the message ID I get from `publish()` and comparing it to the one I get back in `onPublish()`.

```php
<?php

use Mosquitto\Client;

$mid = 0;
$c = new Mosquitto\Client("PHP");
$c->onLog('var_dump');
$c->onConnect(function() use ($c, &$mid) {
    $mid = $c->publish("mgdm/test", "Hello", 2);
});

$c->onPublish(function($publishedId) use ($c, $mid) {
    if ($publishedId == $mid) {
        $c->disconnect();
    }
});

$c->connect("localhost");
$c->loopForever();

```

**Comment by x0tester0x** [comment]
Thanks, I will test it in the weekend.

**Comment by x0tester0x** [comment]
So I tested it right now and it works great :)
Why I have to add an "&" to the variable(&$mid) in the onConnect function, because it works also without it...

**Comment by x0tester0x** [comment]
So I tested it right now and it works, but after publishing the website keeps reloading without ending.
Why I have to add an "&" to the variable(&$mid) in the onConnect function, because it works also without it...

**Comment by rsre** [comment]
> So I tested it right now and it works, but after publishing the website keeps reloading without ending.
> Why I have to add an "&" to the variable(&$mid) in the onConnect function, because it works also without it...

That's because the value of $mid is never changed. So when the program compares its value with $publishedId it's always different because $mid is always 0.

**Comment by x0tester0x** [comment]
So what is the solution? Can you give me an example or add to my Code your solution?

**Comment by rsre** [comment]
I don't quite remember the specifics because this was one month ago and we ended up implementing a different solution. I think we got it working using the example at the [examples directory](https://github.com/mgdm/Mosquitto-PHP/blob/master/examples/pub.php) in the repo, but I might be remembering wrong. Good luck.

**Comment by x0tester0x** [comment]
Ok thanks I will try that. But can you try to remember the specifics I would really appreciate that.

**Comment by gvdhoven** [comment]
@mgdm and @rsre the readme.md needs to be updated to also add the "&" in front of the `$mid` parameter in the `OnPublish` callback. Then this issue can be closed.

```
$c->onPublish(function($publishedId) use ($c, &$mid) {
                if ($publishedId == $mid) {
                        $c->disconnect();
                }
        });
```
